apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name2 }}
spec:
  selector:
    app: nginx2
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}

